// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace JedinicnoTestiranje
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Izračun popusta i pokušaj kupovanja ulaznice.
        /// </summary>
        public void UnosUlaznice()
        {
            #region Variable Declarations
            WinMenuItem uIUlaznicaMenuItem = this.UIProdavačWindow.UIMsIzbornikMenuBar.UIŠifarniciMenuItem.UIUlaznicaMenuItem;
            WinComboBox uINazivprojekcijeComboBox = this.UIProdavačWindow.UIUlaznicaWindow.UICbNazivProjekcijeWindow.UINazivprojekcijeComboBox;
            WinComboBox uISlobodnasjedalaComboBox = this.UIProdavačWindow.UIUlaznicaWindow.UICbDatumWindow.UISlobodnasjedalaComboBox;
            WinList uILbSlobodnaList = this.UIProdavačWindow.UIUlaznicaWindow.UILbSlobodnaWindow.UILbSlobodnaList;
            WinButton uIItemButton = this.UIProdavačWindow.UIUlaznicaWindow.UIItemWindow.UIItemButton;
            WinComboBox uIPopustComboBox = this.UIProdavačWindow.UIUlaznicaWindow.UICbPopustWindow.UIPopustComboBox;
            WinListItem uIItem4ListItem = this.UIProdavačWindow.UIUlaznicaWindow.UILbOdabranaWindow.UIItem4ListItem;
            WinButton uIItemButton1 = this.UIProdavačWindow.UIUlaznicaWindow.UIItemWindow1.UIItemButton;
            WinListItem uIItem6ListItem = this.UIProdavačWindow.UIUlaznicaWindow.UILbOdabranaWindow.UIItem6ListItem;
            WinButton uIDaljeButton = this.UIProdavačWindow.UIUlaznicaWindow.UIDaljeWindow.UIDaljeButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Šifarnici' -> 'Ulaznica' menu item
            Mouse.Click(uIUlaznicaMenuItem, new Point(101, 26));

            // Select 'Stoker (Stoker)' in 'Naziv projekcije:' combo box
            uINazivprojekcijeComboBox.SelectedItem = this.UnosUlazniceParams.UINazivprojekcijeComboBoxSelectedItem;

            // Select '27.6.2013. 17:00' in 'Slobodna sjedala:' combo box
            uISlobodnasjedalaComboBox.SelectedItem = this.UnosUlazniceParams.UISlobodnasjedalaComboBoxSelectedItem;

            // Select '4' in 'lbSlobodna' list box
            uILbSlobodnaList.SelectedItemsAsString = this.UnosUlazniceParams.UILbSlobodnaListSelectedItemsAsString;

            // Click '-->' button
            Mouse.Click(uIItemButton, new Point(21, 8));

            // Select '6' in 'lbSlobodna' list box
            uILbSlobodnaList.SelectedItemsAsString = this.UnosUlazniceParams.UILbSlobodnaListSelectedItemsAsString1;

            // Click '-->' button
            Mouse.Click(uIItemButton, new Point(24, 9));

            // Select 'Umirovljenici' in 'Popust:' combo box
            uIPopustComboBox.SelectedItem = this.UnosUlazniceParams.UIPopustComboBoxSelectedItem;

            // Click '4' list item
            Mouse.Click(uIItem4ListItem, new Point(14, 14));

            // Click '<--' button
            Mouse.Click(uIItemButton1, new Point(29, 20));

            // Click '6' list item
            Mouse.Click(uIItem6ListItem, new Point(16, 8));

            // Click '<--' button
            Mouse.Click(uIItemButton1, new Point(48, 12));

            // Click 'Dalje' button
            Mouse.Click(uIDaljeButton, new Point(42, 20));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(28, 15));
        }
        
        #region Properties
        public virtual UnosUlazniceParams UnosUlazniceParams
        {
            get
            {
                if ((this.mUnosUlazniceParams == null))
                {
                    this.mUnosUlazniceParams = new UnosUlazniceParams();
                }
                return this.mUnosUlazniceParams;
            }
        }
        
        public UIProdavačWindow UIProdavačWindow
        {
            get
            {
                if ((this.mUIProdavačWindow == null))
                {
                    this.mUIProdavačWindow = new UIProdavačWindow();
                }
                return this.mUIProdavačWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UnosUlazniceParams mUnosUlazniceParams;
        
        private UIProdavačWindow mUIProdavačWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'UnosUlaznice'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UnosUlazniceParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Stoker (Stoker)' in 'Naziv projekcije:' combo box
        /// </summary>
        public string UINazivprojekcijeComboBoxSelectedItem = "Stoker (Stoker)";
        
        /// <summary>
        /// Select '27.6.2013. 17:00' in 'Slobodna sjedala:' combo box
        /// </summary>
        public string UISlobodnasjedalaComboBoxSelectedItem = "27.6.2013. 17:00";
        
        /// <summary>
        /// Select '4' in 'lbSlobodna' list box
        /// </summary>
        public string UILbSlobodnaListSelectedItemsAsString = "4";
        
        /// <summary>
        /// Select '6' in 'lbSlobodna' list box
        /// </summary>
        public string UILbSlobodnaListSelectedItemsAsString1 = "6";
        
        /// <summary>
        /// Select 'Umirovljenici' in 'Popust:' combo box
        /// </summary>
        public string UIPopustComboBoxSelectedItem = "Umirovljenici";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIProdavačWindow : WinWindow
    {
        
        public UIProdavačWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Prodavač";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public UIMsIzbornikMenuBar UIMsIzbornikMenuBar
        {
            get
            {
                if ((this.mUIMsIzbornikMenuBar == null))
                {
                    this.mUIMsIzbornikMenuBar = new UIMsIzbornikMenuBar(this);
                }
                return this.mUIMsIzbornikMenuBar;
            }
        }
        
        public UIUlaznicaWindow UIUlaznicaWindow
        {
            get
            {
                if ((this.mUIUlaznicaWindow == null))
                {
                    this.mUIUlaznicaWindow = new UIUlaznicaWindow(this);
                }
                return this.mUIUlaznicaWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMsIzbornikMenuBar mUIMsIzbornikMenuBar;
        
        private UIUlaznicaWindow mUIUlaznicaWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMsIzbornikMenuBar : WinMenuBar
    {
        
        public UIMsIzbornikMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Izbornik";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public UIŠifarniciMenuItem UIŠifarniciMenuItem
        {
            get
            {
                if ((this.mUIŠifarniciMenuItem == null))
                {
                    this.mUIŠifarniciMenuItem = new UIŠifarniciMenuItem(this);
                }
                return this.mUIŠifarniciMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UIŠifarniciMenuItem mUIŠifarniciMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIŠifarniciMenuItem : WinMenuItem
    {
        
        public UIŠifarniciMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "Šifarnici";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIUlaznicaMenuItem
        {
            get
            {
                if ((this.mUIUlaznicaMenuItem == null))
                {
                    this.mUIUlaznicaMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIUlaznicaMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Ulaznica";
                    this.mUIUlaznicaMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIUlaznicaMenuItem.WindowTitles.Add("Prodavač");
                    #endregion
                }
                return this.mUIUlaznicaMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIUlaznicaMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIUlaznicaWindow : WinWindow
    {
        
        public UIUlaznicaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "FrmUlaznica";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public UICbNazivProjekcijeWindow UICbNazivProjekcijeWindow
        {
            get
            {
                if ((this.mUICbNazivProjekcijeWindow == null))
                {
                    this.mUICbNazivProjekcijeWindow = new UICbNazivProjekcijeWindow(this);
                }
                return this.mUICbNazivProjekcijeWindow;
            }
        }
        
        public UICbDatumWindow UICbDatumWindow
        {
            get
            {
                if ((this.mUICbDatumWindow == null))
                {
                    this.mUICbDatumWindow = new UICbDatumWindow(this);
                }
                return this.mUICbDatumWindow;
            }
        }
        
        public UILbSlobodnaWindow UILbSlobodnaWindow
        {
            get
            {
                if ((this.mUILbSlobodnaWindow == null))
                {
                    this.mUILbSlobodnaWindow = new UILbSlobodnaWindow(this);
                }
                return this.mUILbSlobodnaWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UICbPopustWindow UICbPopustWindow
        {
            get
            {
                if ((this.mUICbPopustWindow == null))
                {
                    this.mUICbPopustWindow = new UICbPopustWindow(this);
                }
                return this.mUICbPopustWindow;
            }
        }
        
        public UILbOdabranaWindow UILbOdabranaWindow
        {
            get
            {
                if ((this.mUILbOdabranaWindow == null))
                {
                    this.mUILbOdabranaWindow = new UILbOdabranaWindow(this);
                }
                return this.mUILbOdabranaWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIDaljeWindow UIDaljeWindow
        {
            get
            {
                if ((this.mUIDaljeWindow == null))
                {
                    this.mUIDaljeWindow = new UIDaljeWindow(this);
                }
                return this.mUIDaljeWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICbNazivProjekcijeWindow mUICbNazivProjekcijeWindow;
        
        private UICbDatumWindow mUICbDatumWindow;
        
        private UILbSlobodnaWindow mUILbSlobodnaWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UICbPopustWindow mUICbPopustWindow;
        
        private UILbOdabranaWindow mUILbOdabranaWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        
        private UIDaljeWindow mUIDaljeWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICbNazivProjekcijeWindow : WinWindow
    {
        
        public UICbNazivProjekcijeWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cbNazivProjekcije";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public WinComboBox UINazivprojekcijeComboBox
        {
            get
            {
                if ((this.mUINazivprojekcijeComboBox == null))
                {
                    this.mUINazivprojekcijeComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUINazivprojekcijeComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Naziv projekcije:";
                    this.mUINazivprojekcijeComboBox.WindowTitles.Add("Prodavač");
                    #endregion
                }
                return this.mUINazivprojekcijeComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUINazivprojekcijeComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICbDatumWindow : WinWindow
    {
        
        public UICbDatumWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cbDatum";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public WinComboBox UISlobodnasjedalaComboBox
        {
            get
            {
                if ((this.mUISlobodnasjedalaComboBox == null))
                {
                    this.mUISlobodnasjedalaComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUISlobodnasjedalaComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Slobodna sjedala:";
                    this.mUISlobodnasjedalaComboBox.WindowTitles.Add("Prodavač");
                    #endregion
                }
                return this.mUISlobodnasjedalaComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUISlobodnasjedalaComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UILbSlobodnaWindow : WinWindow
    {
        
        public UILbSlobodnaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "lbSlobodna";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public WinList UILbSlobodnaList
        {
            get
            {
                if ((this.mUILbSlobodnaList == null))
                {
                    this.mUILbSlobodnaList = new WinList(this);
                    #region Search Criteria
                    this.mUILbSlobodnaList.WindowTitles.Add("Prodavač");
                    #endregion
                }
                return this.mUILbSlobodnaList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUILbSlobodnaList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnDodaj";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WinButton.PropertyNames.Name] = "-->";
                    this.mUIItemButton.WindowTitles.Add("Prodavač");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItemButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICbPopustWindow : WinWindow
    {
        
        public UICbPopustWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cbPopust";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIPopustComboBox
        {
            get
            {
                if ((this.mUIPopustComboBox == null))
                {
                    this.mUIPopustComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIPopustComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Popust:";
                    this.mUIPopustComboBox.WindowTitles.Add("Prodavač");
                    #endregion
                }
                return this.mUIPopustComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIPopustComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UILbOdabranaWindow : WinWindow
    {
        
        public UILbOdabranaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "lbOdabrana";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public WinListItem UIItem4ListItem
        {
            get
            {
                if ((this.mUIItem4ListItem == null))
                {
                    this.mUIItem4ListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIItem4ListItem.SearchProperties[WinListItem.PropertyNames.Name] = "4";
                    this.mUIItem4ListItem.WindowTitles.Add("Prodavač");
                    #endregion
                }
                return this.mUIItem4ListItem;
            }
        }
        
        public WinListItem UIItem6ListItem
        {
            get
            {
                if ((this.mUIItem6ListItem == null))
                {
                    this.mUIItem6ListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIItem6ListItem.SearchProperties[WinListItem.PropertyNames.Name] = "6";
                    this.mUIItem6ListItem.WindowTitles.Add("Prodavač");
                    #endregion
                }
                return this.mUIItem6ListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIItem4ListItem;
        
        private WinListItem mUIItem6ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnUkloni";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WinButton.PropertyNames.Name] = "<--";
                    this.mUIItemButton.WindowTitles.Add("Prodavač");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItemButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIDaljeWindow : WinWindow
    {
        
        public UIDaljeWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Dalje";
            this.WindowTitles.Add("Prodavač");
            #endregion
        }
        
        #region Properties
        public WinButton UIDaljeButton
        {
            get
            {
                if ((this.mUIDaljeButton == null))
                {
                    this.mUIDaljeButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDaljeButton.SearchProperties[WinButton.PropertyNames.Name] = "Dalje";
                    this.mUIDaljeButton.WindowTitles.Add("Prodavač");
                    #endregion
                }
                return this.mUIDaljeButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDaljeButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
